#!/bin/bash
# 🦉 BuboIQ Complete Backend Deployment - ONE-COMMAND SCRIPT
# Creates all 17 files needed for Supabase deployment

set -e

echo "🦉 BuboIQ Backend Complete File Generator"
echo "=========================================="
echo ""

# Create directory
TARGET_DIR="$HOME/BuboIQ-Deploy/supabase/functions/make-server-55e8c5b2"
mkdir -p "$TARGET_DIR"
cd "$TARGET_DIR"

echo "📁 Target: $TARGET_DIR"
echo ""
echo "Creating all 17 backend files..."
echo ""

# ============================================================================
# FILE 1: deno.json
# ============================================================================
cat > deno.json << 'DENO_JSON_EOF'
{
  "imports": {
    "hono": "npm:hono@^4.0.0",
    "@supabase/supabase-js": "npm:@supabase/supabase-js@2"
  },
  "compilerOptions": {
    "lib": ["deno.ns", "dom"]
  }
}
DENO_JSON_EOF

echo "✅ 1/17 deno.json"

# ============================================================================
# FILE 2: kv_store.ts
# ============================================================================
cat > kv_store.ts << 'KV_STORE_EOF'
/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

/* Table schema:
CREATE TABLE kv_store_55e8c5b2 (
  key TEXT NOT NULL PRIMARY KEY,
  value JSONB NOT NULL
);
*/

// View at https://supabase.com/dashboard/project/ihlpuumidntrlojvtutx/database/tables

// This file provides a simple key-value interface for storing Figma Make data. It should be adequate for most small-scale use cases.
import { createClient } from "npm:@supabase/supabase-js@2";

const client = () => createClient(
  Deno.env.get("SUPABASE_URL"),
  Deno.env.get("SUPABASE_SERVICE_ROLE_KEY"),
);

// Set stores a key-value pair in the database.
export const set = async (key: string, value: any): Promise<void> => {
  const supabase = client()
  const { error } = await supabase.from("kv_store_55e8c5b2").upsert({
    key,
    value
  });
  if (error) {
    throw new Error(error.message);
  }
};

// Get retrieves a key-value pair from the database.
export const get = async (key: string): Promise<any> => {
  const supabase = client()
  const { data, error } = await supabase.from("kv_store_55e8c5b2").select("value").eq("key", key).maybeSingle();
  if (error) {
    throw new Error(error.message);
  }
  return data?.value;
};

// Delete deletes a key-value pair from the database.
export const del = async (key: string): Promise<void> => {
  const supabase = client()
  const { error } = await supabase.from("kv_store_55e8c5b2").delete().eq("key", key);
  if (error) {
    throw new Error(error.message);
  }
};

// Sets multiple key-value pairs in the database.
export const mset = async (keys: string[], values: any[]): Promise<void> => {
  const supabase = client()
  const { error } = await supabase.from("kv_store_55e8c5b2").upsert(keys.map((k, i) => ({ key: k, value: values[i] })));
  if (error) {
    throw new Error(error.message);
  }
};

// Gets multiple key-value pairs from the database.
export const mget = async (keys: string[]): Promise<any[]> => {
  const supabase = client()
  const { data, error } = await supabase.from("kv_store_55e8c5b2").select("value").in("key", keys);
  if (error) {
    throw new Error(error.message);
  }
  return data?.map((d) => d.value) ?? [];
};

// Deletes multiple key-value pairs from the database.
export const mdel = async (keys: string[]): Promise<void> => {
  const supabase = client()
  const { error } = await supabase.from("kv_store_55e8c5b2").delete().in("key", keys);
  if (error) {
    throw new Error(error.message);
  }
};

// Search for key-value pairs by prefix.
export const getByPrefix = async (prefix: string): Promise<any[]> => {
  const supabase = client()
  const { data, error } = await supabase.from("kv_store_55e8c5b2").select("key, value").like("key", prefix + "%");
  if (error) {
    throw new Error(error.message);
  }
  return data?.map((d) => d.value) ?? [];
};
KV_STORE_EOF

echo "✅ 2/17 kv_store.ts"

# Continue in next message due to size limits...

echo ""
echo "⚠️  This script is incomplete. Due to file size, I'll provide the rest separately."
echo "    Please wait for the complete version..."
